Repository capstone-information-communication/study-with-deeplearning, pull requests merged in 2022-04, with the labels that each got.

#12 Feat: "추가 workbook 동작 퀴리 (#10)"
  backend/src/main/java/core/backend/global/config/QueryDslConfig.java
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookCondition.java
  backend/src/main/java/core/backend/workbook/exception/WorkbookNotFound.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookConditionRepository.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookConditionRepositoryImpl.java
Labels: 🌟 백엔드, 📡 기능

#14 Feat: "추가 member 인증 관련 repository 생성 (#13)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/member/dto/MemberCondition.java
  backend/src/main/java/core/backend/member/exception/MemberNotFound.java
  backend/src/main/java/core/backend/member/repository/MemberCredentialRepository.java
  backend/src/main/java/core/backend/member/repository/MemberCredentialRepositoryImpl.java
Labels: 🌟 백엔드, 📡 기능

#16 Feat: "추가 ProblemService 코드 추가 (#15)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/problem/exception/ProblemNotFound.java
  backend/src/main/java/core/backend/problem/service/ProblemService.java
Labels: 🌟 백엔드, 📡 기능

#18 Feat: "추가 ProblemController 코드 (#17)"
  backend/src/main/java/core/backend/global/dto/DataResponse.java
  backend/src/main/java/core/backend/problem/ProblemController.java
  backend/src/main/java/core/backend/problem/domain/Problem.java
  backend/src/main/java/core/backend/problem/dto/ProblemResponseDto.java
  backend/src/main/java/core/backend/problem/dto/ProblemSaveRequestDto.java
  backend/src/main/java/core/backend/problem/dto/ProblemUpdateRequestDto.java
  backend/src/main/java/core/backend/problem/service/ProblemService.java
Labels: 🌟 백엔드, 📡 기능

#20 workbook service 구현 및 repository 수정
  backend/build.gradle
  backend/src/main/java/core/backend/workbook/dto/WorkbookUpdateRequestDto.java
  backend/src/main/java/core/backend/workbook/entity/Workbook.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookConditionRepository.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookConditionRepositoryImpl.java
  backend/src/main/java/core/backend/workbook/service/WorkbookService.java
Labels: 🌟 백엔드, 📡 기능

#29 Test: "추가 domain 테스트 코드 (#27)"
  backend/src/main/java/core/backend/wrongAnswer/domain/WrongAnswer.java
  backend/src/test/java/core/backend/choice/domain/ChoiceTest.java
  backend/src/test/java/core/backend/commentary/domain/CommentaryTest.java
  backend/src/test/java/core/backend/likeWorkbook/domain/LikeWorkbookTest.java
  backend/src/test/java/core/backend/member/domain/MemberTest.java
  backend/src/test/java/core/backend/question/domain/QuestionTest.java
  backend/src/test/java/core/backend/workbook/domain/WorkbookTest.java
  backend/src/test/java/core/backend/wrongAnswer/domain/WrongAnswerTest.java
Labels: ⛓ 테스트, 🌟 백엔드

#30 Feat: "추가 spring security, jwt 사용하여 사용자 인증 구현 (#24)"
  backend/build.gradle
  backend/src/main/java/core/backend/global/config/WebMvcConfig.java
  backend/src/main/java/core/backend/global/config/WebSecurityConfig.java
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/global/security/JwtAuthenticationFilter.java
  backend/src/main/java/core/backend/global/security/TokenProvider.java
  backend/src/main/java/core/backend/member/exception/ExpiredTokenException.java
  backend/src/main/java/core/backend/member/exception/InvalidTokenException.java
  backend/src/main/java/core/backend/member/exception/WrongTokenException.java
Labels: 🌟 백엔드, 📡 기능

#33 Feat: "추가 question 서비스 코드 작성 (#31)"
  backend/src/main/java/core/backend/question/domain/Question.java
  backend/src/main/java/core/backend/question/dto/QuestionUpdateRequestDto.java
  backend/src/main/java/core/backend/question/exception/QuestionNotFoundException.java
  backend/src/main/java/core/backend/question/repository/QuestionRepository.java
  backend/src/main/java/core/backend/question/service/QuestionService.java
Labels: 🌟 백엔드, 📡 기능

#35 Feat: "추가 choice 서비스 코드 작성 (#34)"
  backend/src/main/java/core/backend/choice/domain/Choice.java
  backend/src/main/java/core/backend/choice/dto/ChoiceUpdateRequestDto.java
  backend/src/main/java/core/backend/choice/exception/ChoiceNotFoundException.java
  backend/src/main/java/core/backend/choice/repository/ChoiceRepository.java
  backend/src/main/java/core/backend/choice/service/ChoiceService.java
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
Labels: 🌟 백엔드, 📡 기능

#48 Feat: "추가 commentary 서비스 코드 작성 (#40)"
  backend/src/main/java/core/backend/commentary/domain/Commentary.java
  backend/src/main/java/core/backend/commentary/dto/CommentaryUpdateRequestDto.java
  backend/src/main/java/core/backend/commentary/exception/CommentaryNotFoundException.java
  backend/src/main/java/core/backend/commentary/repository/CommentaryRepository.java
  backend/src/main/java/core/backend/commentary/service/CommentaryService.java
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
Labels: 🌟 백엔드, 📡 기능

#49 Feat: "추가 member 서비스 코드 작성 (#36)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/member/domain/Member.java
  backend/src/main/java/core/backend/member/dto/MemberPasswordUpdateRequestDto.java
  backend/src/main/java/core/backend/member/dto/MemberUpdateRequestDto.java
  backend/src/main/java/core/backend/member/exception/EmailExistException.java
  backend/src/main/java/core/backend/member/exception/MemberNotFoundException.java
  backend/src/main/java/core/backend/member/exception/NickNameExistException.java
  backend/src/main/java/core/backend/member/exception/SignInFailedException.java
  backend/src/main/java/core/backend/member/repository/MemberConditionRepository.java
  backend/src/main/java/core/backend/member/repository/MemberConditionRepositoryImpl.java
  backend/src/main/java/core/backend/member/repository/MemberRepository.java
  backend/src/main/java/core/backend/member/service/MemberService.java
Labels: 🌟 백엔드, 📡 기능

#51 Feat: "추가 LikeWorkbook 서비스 코드 작성 (#39)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/likeWorkbook/exception/LikeWorkbookNotFoundException.java
  backend/src/main/java/core/backend/likeWorkbook/repository/LikeWorkbookRepository.java
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookService.java
Labels: 🌟 백엔드, 📡 기능

#53 Feat: "추가 controller 테스트를 위한 initDb 코드 작성 (#52)"
  backend/src/main/java/core/backend/initDataBase.java
  backend/src/main/java/core/backend/likeWorkbook/repository/LikeWorkbookRepository.java
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookService.java
Labels: 🌟 백엔드, 📡 기능

#57 Feat: "추가 member 컨트롤러 코드 작성 (#56)"
  backend/src/main/java/core/backend/global/security/TokenProvider.java
  backend/src/main/java/core/backend/member/MemberController.java
  backend/src/main/java/core/backend/member/dto/MemberResponseDto.java
  backend/src/main/java/core/backend/member/dto/MemberSignInRequestDto.java
  backend/src/main/java/core/backend/member/dto/MemberSignInResponseDto.java
  backend/src/main/java/core/backend/member/dto/MemberSignUpRequestDto.java
  backend/src/main/java/core/backend/member/service/MemberService.java
Labels: 🌟 백엔드, 📡 기능

#58 Feat: "추가 question 컨트롤러 코드 (#54)"
  backend/src/main/java/core/backend/question/QuestionController.java
  backend/src/main/java/core/backend/question/dto/QuestionSaveRequestDto.java
Labels: 🌟 백엔드, 📡 기능

#64 Feat: "수정 Commentary과 Question의 일대일 관계를 Embedded를 사용하여 Value Type으로 변…
  backend/src/main/java/core/backend/commentary/domain/Commentary.java
  backend/src/main/java/core/backend/commentary/dto/CommentaryResponseDto.java
  backend/src/main/java/core/backend/commentary/dto/CommentaryUpdateRequestDto.java
  backend/src/main/java/core/backend/commentary/exception/CommentaryNotFoundException.java
  backend/src/main/java/core/backend/commentary/repository/CommentaryRepository.java
  backend/src/main/java/core/backend/commentary/service/CommentaryService.java
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/initDataBase.java
  backend/src/main/java/core/backend/question/QuestionController.java
  backend/src/main/java/core/backend/question/domain/Commentary.java
  backend/src/main/java/core/backend/question/domain/Question.java
  backend/src/main/java/core/backend/question/dto/QuestionResponseDto.java
  backend/src/main/java/core/backend/question/dto/QuestionSaveRequestDto.java
  backend/src/main/java/core/backend/question/dto/QuestionUpdateRequestDto.java
  backend/src/test/java/core/backend/choice/domain/ChoiceTest.java
  backend/src/test/java/core/backend/commentary/domain/CommentaryTest.java
  backend/src/test/java/core/backend/question/domain/QuestionTest.java
Labels: 🌟 백엔드, 🚨 이슈

#65 Feat: "추가 LikeWorkbook 컨트롤러 코드 (#62)"
  backend/src/main/java/core/backend/likeWorkbook/LikeWorkbookController.java
  backend/src/main/java/core/backend/likeWorkbook/dto/LikeWorkbookSaveRequestDto.java
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookService.java
  backend/src/main/java/core/backend/workbook/WorkbookController.java
Labels: 🌟 백엔드, 📡 기능

#66 Feat: "추가 wrongAnswer 컨트롤러 코드 (#61)"
  backend/src/main/java/core/backend/wrongAnswer/WrongAnswerController.java
  backend/src/main/java/core/backend/wrongAnswer/domain/WrongAnswer.java
  backend/src/main/java/core/backend/wrongAnswer/dto/WrongAnswerInfoResponseDto.java
  backend/src/main/java/core/backend/wrongAnswer/dto/WrongAnswerResponseDto.java
  backend/src/main/java/core/backend/wrongAnswer/dto/WrongAnswerSaveRequestDto.java
  backend/src/main/java/core/backend/wrongAnswer/service/WrongAnswerService.java
Labels: 🌟 백엔드, 📡 기능

#68 Feat: "추가 workbook 컨트롤러 Authentication 어노테이션 추가 (#67)"
  backend/.gitignore
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/resources/application.yml
Labels: 🌟 백엔드, 📡 기능

#71 Feat: "추가 workbook id 조회 시 category 별로 분류하여 response 보내는 기능 (#70)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/initDataBase.java
  backend/src/main/java/core/backend/question/dto/QuestionCategoryResponseDto.java
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookCategoryResponseDto.java
  backend/src/main/java/core/backend/workbook/exception/WorkbookNotFoundException.java
  backend/src/main/java/core/backend/workbook/service/WorkbookService.java
Labels: 🌟 백엔드, 📡 기능

#72 Feat: "추가 postman 사용하여 member, workbook, quesiton api 테스트 (#69)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/global/security/JwtAuthenticationFilter.java
  backend/src/main/java/core/backend/member/MemberController.java
  backend/src/main/java/core/backend/member/exception/NotAdminException.java
  backend/src/main/java/core/backend/member/service/MemberService.java
  backend/src/main/java/core/backend/question/dto/QuestionSaveRequestDto.java
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookConditionRepository.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookConditionRepositoryImpl.java
  backend/src/main/java/core/backend/workbook/repository/WorkbookRepository.java
  backend/src/main/java/core/backend/workbook/service/WorkbookService.java
Labels: ⛓ 테스트, 🌟 백엔드
