Repository capstone-information-communication/study-with-deeplearning, pull requests merged in 2022-05, with the labels that each got.

#78 Feat: "추가 initDataBase likeWorkbook, wrongAnswer 데이터 (#74)"
  backend/.gitignore
  backend/src/main/java/core/backend/initDataBase.java
  backend/src/main/resources/application.yml
Labels: 🌟 백엔드, 📡 기능

#82 Refactor: "추가 likeWorkbook facade 패턴 적용하기 (#75)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/likeWorkbook/LikeWorkbookController.java
  backend/src/main/java/core/backend/likeWorkbook/exception/ExistLikeWorkbookException.java
  backend/src/main/java/core/backend/likeWorkbook/exception/LikeWorkbookNotRegisterException.java
  backend/src/main/java/core/backend/likeWorkbook/repository/LikeWorkbookRepository.java
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookFacade.java
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookService.java
Labels: ⚒ 리팩토링, 🌟 백엔드

#84 Refactor: "추가 wrongAnswer facade 패턴 적용하기 (#76)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookCategoryResponseDto.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookInfoResponseDto.java
  backend/src/main/java/core/backend/wrongAnswer/WrongAnswerController.java
  backend/src/main/java/core/backend/wrongAnswer/dto/WrongAnswerInfoResponseDto.java
  backend/src/main/java/core/backend/wrongAnswer/exception/WrongAnswerNotRegisterException.java
  backend/src/main/java/core/backend/wrongAnswer/service/WrongAnswerFacade.java
Labels: ⚒ 리팩토링, 🌟 백엔드

#86 Refactor: "추가 workbook facade 패턴 적용 (#80)"
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookCategoryResponseDto.java
  backend/src/main/java/core/backend/workbook/service/WorkbookFacade.java
  backend/src/main/java/core/backend/workbook/service/WorkbookService.java
Labels: ⚒ 리팩토링, 🌟 백엔드

#88 Feat: "추가 workbook 채점하기 기능 (#87)"
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookCheckRequestDto.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookCheckResponseDto.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookResponseDto.java
  backend/src/main/java/core/backend/workbook/service/WorkbookFacade.java
Labels: 🌟 백엔드, 📡 기능

#91 Test: "추가 workbook 서비스 테스트 코드 (#42)"
  backend/src/test/java/core/backend/workbook/service/WorkbookServiceTest.java
Labels: ⛓ 테스트, 🌟 백엔드

#96 Feat: "프론트엔드 로그인, 회원가입 통신 추가 (#95)"
  frontend/.idea/gradle.xml
  frontend/app/build.gradle
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/com/smp/frontend/Activity/LoginActivity.java
  frontend/app/src/main/java/com/smp/frontend/Activity/RegisterActivity.java
  frontend/app/src/main/java/com/smp/frontend/PreferencesManager.java
  frontend/app/src/main/java/com/smp/frontend/fragment/WorkBookFragment.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/RestApi.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/RetrofitClient.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/SginInResponse.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/SginUpResponse.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/SingletonGson.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/WorkBookResponse.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/WorkBookTestResponse.java
  frontend/app/src/main/res/layout/activity_register.xml
  frontend/gradle/wrapper/gradle-wrapper.properties
Labels: 📡 기능, 🫐 프론트

#100 Feat: "추가 로그아웃과 파일 업로드 구현 (#99)"
  frontend/app/build.gradle
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/com/smp/frontend/Activity/LoginActivity.java
  frontend/app/src/main/java/com/smp/frontend/Activity/MainActivity.java
  frontend/app/src/main/java/com/smp/frontend/Activity/RegisterActivity.java
  frontend/app/src/main/java/com/smp/frontend/PreferencesManager.java
  frontend/app/src/main/java/com/smp/frontend/fragment/HomeFragment.java
  frontend/app/src/main/java/com/smp/frontend/fragment/UploadFragment.java
  frontend/app/src/main/java/com/smp/frontend/restAPi/SginInResponse.java
  frontend/app/src/main/res/layout/activity_register.xml
  frontend/app/src/main/res/layout/fragment_home.xml
  frontend/app/src/main/res/layout/fragment_upload.xml
Labels: 📡 기능, 🫐 프론트

#101 Feat: "추가 파일 업로드 PDF추출 (#99)"
  frontend/app/build.gradle
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/com/smp/frontend/Activity/MainActivity.java
  frontend/app/src/main/java/com/smp/frontend/fragment/UploadFragment.java
Labels: 📡 기능, 🫐 프론트

#102 Feat: "추가 파일 업로드 PDF추출 (#99)"
  frontend/app/src/main/java/com/smp/frontend/fragment/UploadFragment.java
Labels: 📡 기능, 🫐 프론트

#105 Feat: "추가 문제집 생성 시에 pdf의 text까지 가져오는 api (#104)"
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/java/core/backend/workbook/dto/WorkbookWithTextRequestDto.java
Labels: 🌟 백엔드, 📡 기능

#108 Feat: "추가 flask 서버와 통신하여 Question 을 저장하는 기능 (#106)"
  backend/src/main/java/core/backend/choice/dto/ChoiceAIResponseDto.java
  backend/src/main/java/core/backend/global/config/RestTemplateConfig.java
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/question/dto/QuestionAIRequestDto.java
  backend/src/main/java/core/backend/question/dto/QuestionAIResponseDto.java
  backend/src/main/java/core/backend/question/exception/QuestionFlaskResponseException.java
  backend/src/main/java/core/backend/question/service/QuestionAIService.java
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/resources/application.yml
Labels: 🌟 백엔드, 📡 기능

#114 Feat: "추가 오답노트 response에서 questionList를 workbook 안에 넣어서 반환하기 (#113)"
  backend/src/main/java/core/backend/workbook/dto/WorkbookInfoResponseDto.java
  backend/src/main/java/core/backend/wrongAnswer/dto/WrongAnswerInfoResponseDto.java
Labels: 🌟 백엔드, 🚨 이슈

#118 Feat: "추가 deleteById 실행 후에 ResponseEntity 로 response 반환 (#117)"
  backend/src/main/java/core/backend/choice/ChoiceController.java
  backend/src/main/java/core/backend/global/dto/DefaultDeleteResponseDto.java
  backend/src/main/java/core/backend/likeWorkbook/LikeWorkbookController.java
  backend/src/main/java/core/backend/question/QuestionController.java
  backend/src/main/java/core/backend/workbook/WorkbookController.java
  backend/src/main/java/core/backend/wrongAnswer/WrongAnswerController.java
Labels: 🌟 백엔드, 🚨 이슈

#121 Feat: "추가 문제집 채점하기 기능 (#120)"
  frontend/app/src/main/java/com/smp/frontend/common/PreferencesManager.java
  frontend/app/src/main/java/com/smp/frontend/common/WorkBookQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/common/WrongAnswerQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/member/activity/LoginActivity.java
  frontend/app/src/main/java/com/smp/frontend/member/fragment/HomeFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/WorkbookController.java
  frontend/app/src/main/java/com/smp/frontend/workbook/activity/WorkBookQeustion.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/WorkBookCheckRequestDto.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/WorkBookResponseDto.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/WorkBookTestResponse.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/UploadFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/WorkBookFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookItemData.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionAdapter.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionItemData.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/activity/WrongAnswersActivity.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/fragment/WrongAnswerFragment.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswerBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersItemData.java
  frontend/app/src/main/res/layout/activity_work_book_qeustion.xml
  frontend/app/src/main/res/layout/fragment_work_book.xml
Labels: 📡 기능, 🫐 프론트

#129 Refactor: " 추가 UI화면 (#122)"
  frontend/app/src/main/res/drawable-v24/pdf.png
  frontend/app/src/main/res/drawable/radius.xml
  frontend/app/src/main/res/layout/activity_login.xml
  frontend/app/src/main/res/layout/activity_main.xml
  frontend/app/src/main/res/layout/activity_register.xml
  frontend/app/src/main/res/layout/activity_work_book_qeustion.xml
  frontend/app/src/main/res/layout/activity_wrong_answers.xml
  frontend/app/src/main/res/layout/fragment_home.xml
  frontend/app/src/main/res/layout/fragment_upload.xml
  frontend/app/src/main/res/layout/fragment_wrong_answer.xml
  frontend/app/src/main/res/layout/workbook_qeustion_view.xml
  frontend/app/src/main/res/layout/workbook_view.xml
  frontend/app/src/main/res/layout/wrong_answer_workbook_view.xml
  frontend/app/src/main/res/layout/wrong_answers_view.xml
  frontend/app/src/main/res/menu/nav_bar.xml
  frontend/app/src/main/res/values-night/themes.xml
  frontend/app/src/main/res/values/colors.xml
  frontend/app/src/main/res/values/themes.xml
Labels: ⚒ 리팩토링, 🫐 프론트

#132 Feat: "추가 extractedText 3000자 제한, pdf 추출 전 extractedText 초기화 (#131)"
  frontend/app/src/main/java/com/smp/frontend/workbook/activity/WorkBookQeustion.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/UploadFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/activity/WrongAnswersActivity.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswerBookAdapter.java
Labels: 🐞 버그, 🚨 이슈, 🫐 프론트

#134 Feat: "추가 워크북 문제 단답형 추가 (#133)"
  frontend/app/src/main/java/com/smp/frontend/common/WorkBookQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/common/WrongAnswerQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/workbook/activity/WorkBookQeustion.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/WorkBookTestResponse.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionAdapter.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionItemData.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/activity/WrongAnswersActivity.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/dto/WrongAnswerTestResponse.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersItemData.java
  frontend/app/src/main/res/layout/workbook_qeustion_view.xml
  frontend/app/src/main/res/layout/wrong_answers_view.xml
Labels: 📡 기능, 🫐 프론트

#136 Feat: "추가 워크북 문제집 검색 추가 (#135)"
  frontend/.idea/jarRepositories.xml
  frontend/app/build.gradle
  frontend/app/src/main/java/com/smp/frontend/global/PreferencesManager.java
  frontend/app/src/main/java/com/smp/frontend/global/WorkBookQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/global/WrongAnswerQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/global/choiceListDto.java
  frontend/app/src/main/java/com/smp/frontend/global/gsonParsing.java
  frontend/app/src/main/java/com/smp/frontend/member/activity/LoginActivity.java
  frontend/app/src/main/java/com/smp/frontend/member/fragment/HomeFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/WorkbookController.java
  frontend/app/src/main/java/com/smp/frontend/workbook/activity/WorkBookQeustion.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/UploadFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/WorkBookFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookItemData.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionAdapter.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionItemData.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/activity/WrongAnswersActivity.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/fragment/WrongAnswerFragment.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersItemData.java
  frontend/app/src/main/res/layout/activity_main.xml
  frontend/app/src/main/res/layout/fragment_work_book.xml
  frontend/app/src/main/res/values/searchSpinner.xml
  frontend/build.gradle
Labels: 📡 기능, 🫐 프론트

#138 Feat: "추가 문제집 삭제 기능 (#137)"
  frontend/app/src/main/java/com/smp/frontend/workbook/WorkbookController.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/WorkBookFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/RecyclerItemTouchHelper.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/fragment/WrongAnswerFragment.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswerBookAdapter.java
  frontend/app/src/main/res/layout/fragment_work_book.xml
Labels: 📡 기능, 🫐 프론트

#140 Feat: "수정 문제 단답형 버그 (#139)"
  frontend/app/src/main/java/com/smp/frontend/workbook/activity/WorkBookQeustion.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionAdapter.java
  frontend/app/src/main/res/layout/activity_work_book_qeustion.xml
  frontend/app/src/main/res/layout/workbook_qeustion_view.xml
Labels: 🐞 버그, 🚨 이슈, 🫐 프론트

#141 Feat: "추가 오답 문제 service 코드 작성 (#127)"
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/dto/WrongChoiceResponseDto.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/dto/WrongQuestionResponseDto.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/exception/WrongQuestionNotFoundException.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/repository/WrongQuestionRepository.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionService.java
Labels: 🌟 백엔드, 📡 기능

#143 Feat: "추가 wrong figure 데이터를 wrong workbook 에서 member 로 이전 (#142)"
  backend/src/main/java/core/backend/member/domain/Member.java
  backend/src/main/java/core/backend/member/domain/WrongFigure.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/domain/WrongWorkbook.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookService.java
Labels: 🌟 백엔드, 📡 기능

#147 Feat: "추가 오답 문제집 controller 코드 작성 (#144)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/WrongWorkbookController.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/dto/WrongWorkbookResponseDto.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/exception/WrongWorkbookNotYoursException.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/repository/WrongWorkbookRepository.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookService.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookServiceImpl.java
Labels: 🌟 백엔드, 📡 기능

#148 Feat: "추가 오답 문제 controller 코드 작성 (#145)"
  backend/src/main/java/core/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/WrongQuestionController.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/exception/WrongQuestionNotYoursException.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionService.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionServiceImpl.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/repository/WrongWorkbookRepository.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookServiceImpl.java
Labels: 🌟 백엔드, 📡 기능

#149 Feat: "추가 wrongFigure와 wrongWorkbook 등록 (#146)"
  backend/src/main/java/core/backend/initDataBase.java
  backend/src/main/java/core/backend/member/domain/Member.java
  backend/src/main/java/core/backend/member/domain/WrongFigure.java
  backend/src/main/java/core/backend/member/dto/MemberResponseDto.java
  backend/src/main/java/core/backend/member/service/WrongFigureService.java
  backend/src/main/java/core/backend/member/service/WrongFigureServiceImpl.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/domain/WrongQuestion.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionService.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionServiceImpl.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/WrongWorkbookController.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/dto/WrongWorkbookRequestDto.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookServiceImpl.java
  backend/src/main/resources/application.yml
Labels: 🌟 백엔드, 📡 기능

#151 Feat: "수정 문제집 채점 기능 (#150)"
  frontend/app/src/main/java/com/smp/frontend/global/WorkBookQuestionListDto.java
  frontend/app/src/main/java/com/smp/frontend/workbook/WorkbookController.java
  frontend/app/src/main/java/com/smp/frontend/workbook/activity/WorkBookQeustion.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/WorkBookCheckRequestDto.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionAdapter.java
Labels: 📡 기능, 🫐 프론트

#155 Refactor: "추가 오답 문제, 문제집 저장 및 오답 수치 데이터 코드 facade로 묶기 (#153)"
  backend/src/main/java/core/backend/initDataBase.java
  backend/src/main/java/core/backend/member/service/WrongFigureService.java
  backend/src/main/java/core/backend/member/service/WrongFigureServiceImpl.java
  backend/src/main/java/core/backend/wrongProblem/wrongAnswer/WrongAnswerController.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionService.java
  backend/src/main/java/core/backend/wrongProblem/wrongQuestion/service/WrongQuestionServiceImpl.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/WrongWorkbookController.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookFacade.java
  backend/src/main/java/core/backend/wrongProblem/wrongWorkbook/service/WrongWorkbookFacadeImpl.java
Labels: ⚒ 리팩토링, 🌟 백엔드

#156 Feat: "추가 likeCount 증가 및 중복 저장 예외 처리 (#154)"
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookFacade.java
  backend/src/main/java/core/backend/likeWorkbook/service/LikeWorkbookFacadeImpl.java
  backend/src/main/java/core/backend/problem/workbook/domain/Workbook.java
  backend/src/main/java/core/backend/problem/workbook/service/WorkbookService.java
Labels: 🌟 백엔드, 🚨 이슈

#157 Feat: "추가 오답노트 삭제 기능 (#152)"
  frontend/app/src/main/java/com/smp/frontend/workbook/WorkbookController.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/WorkBookTestResponse.java
  frontend/app/src/main/java/com/smp/frontend/workbook/dto/likeWorkBook.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/UploadFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/fragment/WorkBookFragment.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookItemData.java
  frontend/app/src/main/java/com/smp/frontend/workbook/list/WorkBookQuestionAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/WrongAnswerController.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/activity/WrongAnswersActivity.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/dto/WrongAnswerTestResponse.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/fragment/WrongAnswerFragment.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/RecyclerItemTouchHelperWrong.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswerBookAdapter.java
  frontend/app/src/main/java/com/smp/frontend/wrongAnswer/list/WrongAnswersAdapter.java
  frontend/app/src/main/res/drawable/ic_baseline_favorite_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_favorite_border_24.xml
  frontend/app/src/main/res/layout/workbook_view.xml
  frontend/app/src/main/res/layout/wrong_answers_view.xml
Labels: 📡 기능, 🫐 프론트
